# Generated by Django 5.1.7 on 2025-03-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('photo', models.CharField(max_length=100)),
            ],
        ),
    ]
