# Generated by Django 5.1.7 on 2025-03-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='category',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('STAR', 'Star'), ('GALAXY', 'Galaxy')], default='', max_length=100),
        ),
    ]
