# Generated by Django 5.1.7 on 2025-03-20 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photograph_publicated'),
    ]

    operations = [
        migrations.AddField(
            model_name='photograph',
            name='photo_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
